name: Build APK WanaboyAI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 🔥 Java FIX (ini penting)
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    # System deps
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo6 cmake \
          libffi-dev libssl-dev

    # Python deps
    - name: Install Python Deps
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    # 🔥 Android SDK resmi (ANTI ERROR)
    - name: Setup Android
      uses: android-actions/setup-android@v3

    # 🔥 INSTALL SDK FIX
    - name: Install SDK Components
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-31"
        sdkmanager "build-tools;31.0.0"

        yes | sdkmanager --licenses

    # Build APK
    - name: Build APK
      run: |
        buildozer android debug

    # Upload hasil
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: WanaboyAI
        path: bin/*.apk
